module.exports = {
    singUp:"userSignUp",
    login:"login",
    getUser:"user_find",
    forgotPassword:"reset",
    getNotes:"getNotesList",
    setNotes:"addNotes",
    deleteNote:"trashNotes",
    updateNotes:"updateNotes",
    addUpdateReminderNotes:"addUpdateReminderNotes",
    removeReminderNotes:"removeReminderNotes",
    changesColorNotes:"changesColorNotes",
    archiveNotes:"archiveNotes",
    deleteForeverNotes:"deleteForeverNotes",
    GetNoteLabelList:'getNoteLabelList',
    UploadProfileImage:'uploadProfileImage',
    SearchUserList:'searchUserList',
    Productcarts:'productcarts'
}